apiVersion: v1
kind: Secret
metadata:
  name: {{ include "askme.fullname" . }}-secrets
  namespace: {{ .Values.client.namespace }}
  labels:
    {{- include "askme.labels" . | nindent 4 }}
  annotations:
    askme.avanteam.com/client: {{ .Values.client.name }}
    askme.avanteam.com/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  # Azure OpenAI
  AZURE_OPENAI_RESOURCE: {{ .Values.azure.openai.resource | quote }}
  AZURE_OPENAI_ENDPOINT: {{ .Values.azure.openai.endpoint | quote }}
  AZURE_OPENAI_KEY: {{ .Values.azure.openai.key | quote }}
  AZURE_OPENAI_MODEL: {{ .Values.azure.openai.model | quote }}
  AZURE_OPENAI_MODEL_NAME: {{ .Values.azure.openai.modelName | quote }}
  AZURE_OPENAI_TEMPERATURE: {{ .Values.azure.openai.temperature | quote }}
  AZURE_OPENAI_TOP_P: {{ .Values.azure.openai.topP | quote }}
  AZURE_OPENAI_STOP_SEQUENCE: ""
  AZURE_OPENAI_SEED: ""
  AZURE_OPENAI_CHOICES_COUNT: "1"
  AZURE_OPENAI_PRESENCE_PENALTY: "0.0"
  AZURE_OPENAI_FREQUENCY_PENALTY: "0.0"
  AZURE_OPENAI_LOGIT_BIAS: ""
  AZURE_OPENAI_USER: ""
  AZURE_OPENAI_TOOLS: ""
  AZURE_OPENAI_TOOL_CHOICE: ""
  AZURE_OPENAI_STREAM: {{ .Values.azure.openai.stream | quote }}
  AZURE_OPENAI_SYSTEM_MESSAGE: {{ .Values.azure.openai.systemMessage | quote }}
  AZURE_OPENAI_PREVIEW_API_VERSION: {{ .Values.azure.openai.previewApiVersion | quote }}
  AZURE_OPENAI_EMBEDDING_NAME: {{ .Values.azure.openai.embeddingName | quote }}
  AZURE_OPENAI_EMBEDDING_ENDPOINT: {{ .Values.azure.openai.embeddingEndpoint | quote }}
  AZURE_OPENAI_EMBEDDING_KEY: {{ .Values.azure.openai.embeddingKey | quote }}
  AZURE_OPENAI_RESPONSE_VERY_SHORT_MAX_TOKENS: {{ .Values.azure.openai.responseVeryShortMaxTokens | quote }}
  AZURE_OPENAI_RESPONSE_NORMAL_MAX_TOKENS: {{ .Values.azure.openai.responseNormalMaxTokens | quote }}
  AZURE_OPENAI_RESPONSE_COMPREHENSIVE_MAX_TOKENS: {{ .Values.azure.openai.responseComprehensiveMaxTokens | quote }}

  # Claude AI
  CLAUDE_API_KEY: {{ .Values.claude.apiKey | quote }}
  CLAUDE_MODEL: {{ .Values.claude.model | quote }}
  CLAUDE_TEMPERATURE: {{ .Values.claude.temperature | quote }}
  CLAUDE_TOP_P: {{ .Values.claude.topP | quote }}
  CLAUDE_SYSTEM_MESSAGE: {{ .Values.claude.systemMessage | quote }}
  CLAUDE_RESPONSE_VERY_SHORT_MAX_TOKENS: {{ .Values.claude.responseVeryShortMaxTokens | quote }}
  CLAUDE_RESPONSE_NORMAL_MAX_TOKENS: {{ .Values.claude.responseNormalMaxTokens | quote }}
  CLAUDE_RESPONSE_COMPREHENSIVE_MAX_TOKENS: {{ .Values.claude.responseComprehensiveMaxTokens | quote }}

  # OpenAI Direct
  OPENAI_DIRECT_API_KEY: {{ .Values.openai.apiKey | quote }}
  OPENAI_DIRECT_MODEL: {{ .Values.openai.model | quote }}
  OPENAI_DIRECT_TEMPERATURE: {{ .Values.openai.temperature | quote }}
  OPENAI_DIRECT_TOP_P: {{ .Values.openai.topP | quote }}
  OPENAI_DIRECT_STOP_SEQUENCE: ""
  OPENAI_DIRECT_BASE_URL: {{ .Values.openai.baseUrl | quote }}
  OPENAI_DIRECT_SYSTEM_MESSAGE: {{ .Values.openai.systemMessage | quote }}
  OPENAI_DIRECT_RESPONSE_VERY_SHORT_MAX_TOKENS: {{ .Values.openai.responseVeryShortMaxTokens | quote }}
  OPENAI_DIRECT_RESPONSE_NORMAL_MAX_TOKENS: {{ .Values.openai.responseNormalMaxTokens | quote }}
  OPENAI_DIRECT_RESPONSE_COMPREHENSIVE_MAX_TOKENS: {{ .Values.openai.responseComprehensiveMaxTokens | quote }}

  # Mistral AI
  MISTRAL_API_KEY: {{ .Values.mistral.apiKey | quote }}
  MISTRAL_MODEL: {{ .Values.mistral.model | quote }}
  MISTRAL_TEMPERATURE: {{ .Values.mistral.temperature | quote }}
  MISTRAL_TOP_P: {{ .Values.mistral.topP | quote }}
  MISTRAL_SYSTEM_MESSAGE: {{ .Values.mistral.systemMessage | quote }}
  MISTRAL_RESPONSE_VERY_SHORT_MAX_TOKENS: {{ .Values.mistral.responseVeryShortMaxTokens | quote }}
  MISTRAL_RESPONSE_NORMAL_MAX_TOKENS: {{ .Values.mistral.responseNormalMaxTokens | quote }}
  MISTRAL_RESPONSE_COMPREHENSIVE_MAX_TOKENS: {{ .Values.mistral.responseComprehensiveMaxTokens | quote }}

  # Gemini AI
  GEMINI_API_KEY: {{ .Values.gemini.apiKey | quote }}
  GEMINI_MODEL: {{ .Values.gemini.model | quote }}
  GEMINI_TEMPERATURE: {{ .Values.gemini.temperature | quote }}
  GEMINI_TOP_P: {{ .Values.gemini.topP | quote }}
  GEMINI_SYSTEM_MESSAGE: {{ .Values.gemini.systemMessage | quote }}
  GEMINI_RESPONSE_VERY_SHORT_MAX_TOKENS: {{ .Values.gemini.responseVeryShortMaxTokens | quote }}
  GEMINI_RESPONSE_NORMAL_MAX_TOKENS: {{ .Values.gemini.responseNormalMaxTokens | quote }}
  GEMINI_RESPONSE_COMPREHENSIVE_MAX_TOKENS: {{ .Values.gemini.responseComprehensiveMaxTokens | quote }}

  # Azure Search
  AZURE_SEARCH_SERVICE: {{ .Values.azure.search.service | quote }}
  AZURE_SEARCH_INDEX: {{ .Values.azure.search.index | quote }}
  AZURE_SEARCH_KEY: {{ .Values.azure.search.key | quote }}

  # Azure Speech
  AZURE_SPEECH_KEY: {{ .Values.azure.speech.key | quote }}
  AZURE_SPEECH_REGION: {{ .Values.azure.speech.region | quote }}

  # Azure CosmosDB
  AZURE_COSMOSDB_ACCOUNT: {{ .Values.azure.cosmosdb.account | quote }}
  AZURE_COSMOSDB_DATABASE: {{ .Values.azure.cosmosdb.database | quote }}
  AZURE_COSMOSDB_CONVERSATIONS_CONTAINER: {{ .Values.azure.cosmosdb.conversationsContainer | quote }}
  AZURE_COSMOSDB_ACCOUNT_KEY: {{ .Values.azure.cosmosdb.key | quote }}
  AZURE_COSMOSDB_ENABLE_FEEDBACK: {{ .Values.azure.cosmosdb.enableFeedback | quote }}

  # Avanteam Custom
  AVANTEAM_AUTH_TOKEN: {{ .Values.avanteam.authToken | quote }}
  AVANTEAM_LICENCEHUB_HANDLERURL: {{ .Values.avanteam.licenceHubHandlerUrl | quote }}
  AVANTEAM_LICENCEHUB_KEY: {{ .Values.avanteam.licenceHubKey | quote }}

  # MS Defender
  MS_DEFENDER_ENABLED: {{ .Values.msDefender.enabled | quote }}
  MS_DEFENDER_ENDPOINT: {{ .Values.msDefender.endpoint | quote }}
  MS_DEFENDER_KEY: {{ .Values.msDefender.key | quote }}